# Generated by Django 3.2.6 on 2022-06-16 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('key', models.UUIDField(default=uuid.UUID('0e3f1db1-1362-4013-bafa-067cf3fb5c37'))),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('description', models.TextField(default='COVID19 point')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('check_date', models.DateTimeField(null=True)),
                ('address', models.TextField(default='Some address')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Low risk level'), (2, 'Medium risk level'), (3, 'High level of danger')], default=1)),
                ('point_source', models.CharField(choices=[('building', 'Point from institution'), ('user', 'Point from user'), ('confirmed', 'Confirmed infected point')], default='user', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Unchecked',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.point')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.IntegerField(null=True)),
                ('building', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.building')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Banned',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(default='Spam')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
