# Generated by Django 3.2.6 on 2022-06-17 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='building',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.building'),
        ),
        migrations.AddField(
            model_name='point',
            name='from_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='building',
            name='key',
            field=models.UUIDField(default=uuid.UUID('e65e0dea-420d-4b81-bf42-a1f1822f470b')),
        ),
        migrations.AlterField(
            model_name='point',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='point',
            name='point_source',
            field=models.CharField(default='user', max_length=10),
        ),
        migrations.DeleteModel(
            name='Unchecked',
        ),
    ]
