# Generated by Django 3.2.6 on 2022-06-17 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220617_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='key',
            field=models.UUIDField(default=uuid.UUID('b72091b0-1b12-43a4-a5b7-9d6ac3d4b5a7')),
        ),
    ]
