# Generated by Django 3.2.6 on 2022-06-17 14:42

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_alter_building_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='key',
            field=models.UUIDField(default=uuid.UUID('fc15038e-ded8-4b40-a341-71d5d2407352')),
        ),
        migrations.AlterField(
            model_name='point',
            name='building',
            field=models.ManyToManyField(to='home.Building'),
        ),
        migrations.AlterField(
            model_name='point',
            name='from_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
