# Generated by Django 3.2.6 on 2022-06-17 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220617_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='key',
            field=models.UUIDField(default=uuid.UUID('2a4e8d1f-fa3c-497b-9ba7-c58310207941')),
        ),
    ]
