# Generated by Django 3.2.6 on 2022-06-17 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_alter_building_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='key',
            field=models.UUIDField(default=uuid.UUID('833e5523-3876-49c8-9024-f8220d3263e5')),
        ),
        migrations.RemoveField(
            model_name='point',
            name='building',
        ),
        migrations.AddField(
            model_name='point',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.building'),
        ),
        migrations.RemoveField(
            model_name='point',
            name='from_user',
        ),
        migrations.AddField(
            model_name='point',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
