# Generated by Django 3.2.6 on 2022-06-18 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220617_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='key',
            field=models.UUIDField(default=uuid.UUID('1a3b930b-e787-482e-a9ce-c8a0468da19f')),
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
    ]
